TrajectoryPlannerROS:
  # max_vel_x: 0.2
  # min_vel_x: 0.1
  max_vel_x: 0.28
  min_vel_x: 0.15
  max_rotational_vel: 0.2
  min_in_place_rotational_vel: 0.1
  backup_vel: -0.15

  sim_time: 2.0
  path_distance_bias: 0.6
  goal_distance_bias: 0.6

  acc_limit_th: 3.5
  acc_limit_x: 2.5
  acc_limit_y: 2.5

  holonomic_robot: false
