armario:
- - 2.481996181460269
  - 0.02401788444637336
- - 0.0
  - 0.0
  - -0.022859016662104006
  - 0.9997386985393941
sofa_longe:
- - 1.6360487084736033
  - -1.4812065926716398
- - 0.0
  - 0.0
  - -0.9990112466335778
  - 0.04445817247283994
sofa_perto:
- - -0.08917764610785954
  - -1.2261741416636245
- - 0.0
  - 0.0
  - 0.9954260869912693
  - 0.09553483834314021
mesa:
- - 0.06074335457406042
  - -3.687040947498084
- - 0.0
  - 0.0
  - -0.9844955484533768
  - 0.1754095638084901
entrada:
- - 1.990756348119751
  - -3.0653452248993083
- - 0.0
  - 0.0
  - 0.9845262932112621
  - 0.17523691955661647
jardim:
- - 2.6781804489258185
  - -4.842972948370255
- - 0.0
  - 0.0
  - 0.6453906449573462
  - 0.7638526791217929
pessoa_longe:
- - 0.6083431107939908
  - -1.1990321688916115
- - 0.0
  - 0.0
  - -0.011070029530613923
  - 0.9999387253458041
pessoa_perto:
- - 2.048323812484649
  - -1.4008600863176568
- - 0.0
  - 0.0
  - -0.048293197941305495
  - 0.9988332028084579
saida:
- - -2.959229347603788
  - 0.7628495279201201
- - 0.0
  - 0.0
  - -0.8817421079783833
  - 0.471731761722525
