inicio:
- - 14.0744424326
  - -0.652677076638
- - 0.0
  - 0.0
  - 0.0339919835976
  - 0.999422105545
mesa_objeto:
- - 12.8643860991
  - -3.8424949914
- - 0.0
  - 0.0
  - -0.999892212008
  - -0.0146821103701
social:
- - 14.5198194245
  - -3.51013625543
- - 0.0
  - 0.0
  - -0.685887834262
  - 0.727707275497
achou_pessoa:
- - 13.2201516025
  - -4.51972842437
- - 0.0
  - 0.0
  - -0.558772008085
  - 0.829321314679
pessoal:
- - 14.6399435955
  - -5.83399343764
- - 0.0
  - 0.0
  - -0.64407964523
  - 0.764958437172
intima:
- - 14.665624828
  - -6.67070833888
- - 0.0
  - 0.0
  - -0.708436067396
  - 0.705774991348
pessoa:
- - 14.6517558149
  - -7.09085593879
- - 0.0
  - 0.0
  - -0.710997471755
  - 0.703194564227
pa_inicio:
- - 2.17340170858
  - -4.27596806381
- - 0.0
  - 0.0
  - 0.852640164354
  - 0.522498564716
pa_mesa:
- - 3.29161470444
  - -1.64982593277
- - 0.0
  - 0.0
  - 0.173648177667
  - 0.984807753012
pa_centro:
- - 2.48758357455
  - -1.95821528354
- - 0.0
  - 0.0
  - 0.999961923064
  - -0.00872653549837
pa_arquivo:
- - 1.51285298065
  - -2.09290335018
- - 0.0
  - 0.0
  - 0.887010833178
  - -0.461748613235
pa_intima_p:
- - 3.46640461418
  - -0.600790799087
- - 0.0
  - 0.0
  - 0.113203213768
  - 0.993571855677
pa_pessoal_p:
- - 2.57134509779
  - -0.570707623924
- - 0.0
  - 0.0
  - 0.121869343405
  - 0.992546151641
pa_intima_s:
- - 2.1600856203
  - -0.451735441126
- - 0.0
  - 0.0
  - 0.5
  - 0.866025403784
pa_pessoal_s:
- - 1.6607392176
  - -0.983199512424
- - 0.0
  - 0.0
  - 0.5
  - 0.866025403784
pa_porta_lateral:
- - 0.0334658329985
  - 0.0498976079515
- - 0.0
  - 0.0
  - 0.15643446504
  - 0.987688340595
mesa_casa:
- - 3.864707691718107
  - 0.4136563321866013
- - 0.0
  - 0.0
  - 0.4383711467890774
  - 0.898794046299167
cozinha_casa:
- - 6.1502893268773855
  - 0.7144256996863912
- - 0.0
  - 0.0
  - 0.4617486132350339
  - -0.8870108331782217
corredor_casa_indo_sala:
- - 4.367230265780391
  - 1.9932207617053286
- - 0.0
  - 0.0
  - 0.4146932426562392
  - -0.9099612708765431
corredor_casa_indo_cozinha:
- - 4.131708107024241
  - 1.9780056118108287
- - 0.0
  - 0.0
  - 0.9099612708765432
  - 0.4146932426562389
armario_casa:
- - 2.3751767461870266
  - 1.271445404547
- - 0.0
  - 0.0
  - 0.9455185755993168
  - -0.3255681544571564
sala_casa:
- - 2.494449703151341
  - 0.5660124677037102
- - 0.0
  - 0.0
  - 0.8141155183563192
  - -0.5807029557109398
sofa_casa:
- - 1.4809823373089546
  - 0.8008076084662644
- - 0.0
  - 0.0
  - 0.9510565162951536
  - -0.30901699437494734
entrada_casa:
- - 0.3977871978549745
  - -0.212462345848513
- - 0.0
  - 0.0
  - 0.8571673007021122
  - 0.5150380749100544
corredor_humanoide:
- - 0.13265056185758697
  - 3.5065966755542783
- - 0.0
  - 0.0
  - 0.29237170472273677
  - 0.9563047559630354
test_mesa:
- - 3.878753967803807
  - 0.42167594249924933
- - 0.0
  - 0.0
  - -0.6838134837973778
  - 0.7296568504282634
test_cozinha:
- - 6.050942023153167
  - 0.5967088453588532
- - 0.0
  - 0.0
  - 0.9777753775003815
  - 0.20965521971557596
test_corredor:
- - 4.409341008215418
  - 1.9602721695062395
- - 0.0
  - 0.0
  - -0.9986881393179327
  - 0.05120547222402634
test_sala:
- - 2.519613562071117
  - 0.30838093561927366
- - 0.0
  - 0.0
  - 0.9212296164763403
  - 0.38901927166511313
test_armario:
- - 2.3608924197785486
  - 1.0781789290250865
- - 0.0
  - 0.0
  - 0.7254616932948554
  - 0.6882625455171603
test_sofa_l:
- - 1.5725156042970496
  - 0.3923324604223597
- - 0.0
  - 0.0
  - 0.9487586797496605
  - 0.31600153100844464
test_sofa_p:
- - 1.3694721525061437
  - 0.8526717158883553
- - 0.0
  - 0.0
  - 0.7499434528730239
  - 0.6615019406569316
test_entrada:
- - 0.3474583800485539
  - -0.4503485530531578
- - 0.0
  - 0.0
  - -0.0354750754866
  - 0.999370561413
test_saida:
- - 0.008742411557872788
  - 0.772787404983738
- - 0.0
  - 0.0
  - 0.8358022717709257
  - 0.5490305660913241
