1:
- - 2.0366282290752666
  - 1.7385981858146868
- - 0.0
  - 0.0
  - 0.2308795825551493
  - 0.9729823319871538
2:
- - 1.067045805511079
  - -0.43502863708056505
- - 0.0
  - 0.0
  - -0.9824252705405924
  - 0.18665633609187726
3:
- - 0.00567930605976387
  - -0.8657179858499995
- - 0.0
  - 0.0
  - -0.9835133526663404
  - 0.18083551953920618
4:
- - 0.9706672722302935
  - -2.9235754805070067
- - 0.0
  - 0.0
  - -0.9572217822113914
  - 0.28935524819855507
5:
- - 2.5869568555929923
  - -1.5019928168872259
- - 0.0
  - 0.0
  - -0.974722295438904
  - 0.22341988894078807
6:
- - 3.6866250961036915
  - -2.6603025066466146
- - 0.0
  - 0.0
  - 0.9634663836526689
  - 0.267829288113246
7:
- - 0.4556629214161335
  - -0.547230460408123
- - 0.0
  - 0.0
  - 0.22793013039256232
  - 0.9736774905784921
8:
- - 2.2024428159256226
  - 0.22225362303914262
- - 0.0
  - 0.0
  - 0.2032157280118693
  - 0.9791339887311674
9:
- - -2.7770781246789684
  - -0.35649143416937534
- - 0.0
  - 0.0
  - -0.9737091414971064
  - 0.22779488090158634
